/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

DROP TABLE IF EXISTS `wpda_sas_grade`;
DROP TABLE IF EXISTS `wpda_sas_class`;
DROP TABLE IF EXISTS `wpda_sas_course`;
DROP TABLE IF EXISTS `wpda_sas_student`;
DROP TABLE IF EXISTS `wpda_sas_teacher`;
DROP TABLE IF EXISTS `wpda_sas_module`;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
